# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:
        |
        mvn -v
        mvn install --file initial/pom.xml
        mvn -B package --file complete/pom.xml
    - name: view Maven build file
      run:
        |
        cd complete/target
        ls -lrt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: gs-maven-0.1.0.jar 
          path: complete/target  
    - name: folder creation
      run:
        |
        cd /home
        cd ..
        mkdir /home/runner/work/spring_maven/spring_maven/artifact
        cd /home/runner/work/spring_maven/spring_maven/artifact/
        pwd
        ls
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
          name: gs-maven-0.1.0.jar 
          path: /home/runner/work/spring_maven/spring_maven/artifact/  
    - name: List Downloaded Files (Optional)
      run:
        |
        cd /home/runner/work/spring_maven/spring_maven/artifact/
        pwd
        ls -ltr
    - name: Publish to GitHub Packages
      run: |
        cp /home/runner/work/spring_maven/spring_maven/artifact/gs-maven-0.1.0.jar  https://github.com/keshardevops/gcp-jenkins-demo/packages/
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
